secrets:
- kmsKeyName: projects/celo-testnet/locations/global/keyRings/celo-keyring/cryptoKeys/github-key
  secretEnv:
    NPM_TOKEN: CiQAW8Jnkt+36pMkdh5OQyeaAyAzhGv/3DR5x5boNb9hagV5FboSTQAZggEuJi27vYGa0qAPwxnFRLXK0KlNv9uA9k54oTETN7VeGX8v02YxhzFwJ8ZIqpOe4FOhAfvSTqO0qCsAqtKy/cVXinNkS5wUpNxN
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', 'Dockerfile.androidbuild', '.' ]
  env: ['COMMIT_SHA=$COMMIT_SHA']
  secretEnv: ['NPM_TOKEN']
  waitFor: ["-"]
timeout: 900s
